#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
SCRIPT_LOCATION="$0"
while [ -h "$SCRIPT_LOCATION" ] ; do
    ls=`ls -ld "$SCRIPT_LOCATION"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        SCRIPT_LOCATION="$link"
    else
        SCRIPT_LOCATION=`dirname "$SCRIPT_LOCATION"`/"$link"
    fi
done
APP_HOME=`dirname "$SCRIPT_LOCATION"`
cd "$APP_HOME" || exit 1
APP_HOME=`pwd`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or 1024, whichever is lower
DEFAULT_JVM_OPTS=''

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        exit 1
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || { echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."; exit 1; }
fi

# Set the classpath
GRADLE_WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
if [ ! -e "$GRADLE_WRAPPER_JAR" ] ; then
    echo "ERROR: $GRADLE_WRAPPER_JAR not found"
    exit 1
fi

# Collect all arguments
ARGS="$@"

# Execute Gradle
exec "$JAVACMD" -classpath "$GRADLE_WRAPPER_JAR" \
    "-Dorg.gradle.appname=gradlew" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
